# Generated by Django 6.0.6 on 2026-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('COURANT', 'Courant'), ('EPARGNE', 'Épargne')], max_length=10)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte',
                'db_table': 'compte',
            },
        ),
    ]
