# Generated by Django 6.0.6 on 2026-06-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='utilisateurs.agent'),
        ),
        migrations.AddField(
            model_name='compte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='utilisateurs.client'),
        ),
    ]
