# Generated by Django 6.0.6 on 2026-06-16 00:09

import django.db.models.deletion
import transferts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=transferts.models.generer_reference_transfert, editable=False, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='SUCCES', max_length=10)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('compte_dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_recus', to='comptes.compte')),
                ('compte_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_emis', to='comptes.compte')),
            ],
            options={
                'verbose_name': 'Transfert',
                'db_table': 'transfert',
            },
        ),
    ]
