# Generated by Django 6.0.6 on 2026-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('OUVERTURE_COMPTE', 'Ouverture de compte'), ('SUSPENSION_COMPTE', 'Suspension de compte'), ('REACTIVATION_COMPTE', 'Réactivation de compte')], max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Action Agent',
                'db_table': 'action_agent',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LogSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_ECHEC', 'Tentative échouée')], max_length=20)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de sécurité',
                'db_table': 'log_securite',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'db_table': 'parametre',
                'ordering': ['cle'],
            },
        ),
    ]
