# Generated by Django 6.0.6 on 2026-06-16 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_initial'),
        ('rapports', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='utilisateurs.agent'),
        ),
        migrations.AddField(
            model_name='actionagent',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_agent', to='comptes.compte'),
        ),
        migrations.AddField(
            model_name='logsecurite',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
