# Generated by Django 6.0.6 on 2026-06-16 00:09

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('transferts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=transactions.models.generer_reference_transaction, editable=False, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('TRANSFERT_DEBIT', 'Transfert Débit'), ('TRANSFERT_CREDIT', 'Transfert Crédit')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='SUCCES', max_length=10)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='comptes.compte')),
                ('transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transferts.transfert')),
            ],
            options={
                'verbose_name': 'Transaction',
                'db_table': 'transaction',
                'ordering': ['-date_heure'],
            },
        ),
    ]
